### PR TITLE
Update vpn-gateway-about-vpn-devices.md

### PR DESCRIPTION
**Pull request by Daniel-Pires**
Lines 59 and 69 differs from EN-US version

Comparing EN-US and PT-BR versions of this doc found two differences so far:

| Fortinet |FortiGate |FortiOS 5.4.x |[Configuration instructions](http://cookbook.fortinet.com/ipsec-vpn-microsoft-azure-54) |[Configuration instructions](http://cookbook.fortinet.com/ipsec-vpn-microsoft-azure-54) |
| Fortinet |FortiGate |FortiOS 5.2.7 |[Instruções de configuração](http://docs.fortinet.com/d/fortigate-configuring-ipsec-vpn-between-a-fortigate-and-microsoft-azure) |[Instruções de configuração](http://docs.fortinet.com/d/fortigate-configuring-ipsec-vpn-between-a-fortigate-and-microsoft-azure) |

| WatchGuard |All |Fireware XTM<br> PolicyBased: v11.11.x<br>RouteBased: v11.12.x |[Configuration instructions](http://watchguardsupport.force.com/publicKB?type=KBArticle&SFDCID=kA2F00000000LI7KAM&lang=en_US) |[Configuration instructions](http://watchguardsupport.force.com/publicKB?type=KBArticle&SFDCID=kA22A000000XZogSAG&lang=en_US)|
| Watchguard |Todos |Fireware XTM v11.x |[Instruções de configuração](http://customers.watchguard.com/articles/Article/Configure-a-VPN-connection-to-a-Windows-Azure-virtual-network) |Não compatível |

This caused confusion with a few of my Customers already and also caused cases to be created since Customers were using the version different than minimun.

### CODE REVIEW

**Comment by gosali** [comment]
Hi @Daniel-Pires, we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by Daniel-Pires** [comment]
Sorry but could not understand the final decision …

**Comment by gosali** [comment]
Hi @Daniel-Pires, we are still in discussing, will update the decision later soon.

Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@Daniel-Pires  Thank you for your feedback and suggestion! 
		
The English source file is updated, your feedback is considered when we localize the new version. We will publish the new version of this article very soon. 
		
Microsoft C&E Localization Team

**Pull request closed without merging**
